services:
  dialogue:
    command: --debug --host mosquitto --port 1883 --site-id default --session-timeout
      30 --sound wake /usr/lib/rhasspy/etc/wav/beep_hi.wav --sound recorded /usr/lib/rhasspy/etc/wav/beep_lo.wav
      --sound error /usr/lib/rhasspy/etc/wav/beep_error.wav
    depends_on:
    - mqtt
    image: rhasspy/rhasspy-dialogue-hermes
    tty: true
  intent_recognition:
    command: --intent-graph /profiles/de/intent_graph.pickle.gz --debug --host mosquitto
      --port 1883 --site-id default --replace-numbers --language de_DE --casing lower
    depends_on:
    - mqtt
    image: rhasspy/rhasspy-nlu-hermes
    tty: true
    volumes:
    - /profiles:/profiles
  microphone:
    command: --sample-rate 16000 --sample-width 2 --channels 1 --record-command 'sox
      -t alsa sysdefault:CARD=seeed4micvoicec -t raw -b 16 -c 1 -r 16k - -q noisered
      /home/noise_sox.prof 0.21 compand 0.1,0.1 -inf,-42.1,-inf,-42,-42 0 -90 0.1'
      --debug --host mosquitto --port 1883 --site-id default --list-command 'arecord
      -L' --test-command 'arecord -q -Dsysdefault:CARD=seeed4micvoicec -r 16000 -f
      S16_LE -t raw'
    depends_on:
    - mqtt
    devices:
    - /dev/snd
    image: rhasspy/rhasspy-microphone-cli-hermes
    tty: true
  speakers:
    command: --play-command 'aplay -q -t wav' --list-command 'aplay -L' --debug --host
      mosquitto --port 1883 --site-id default
    depends_on:
    - mqtt
    devices:
    - /dev/snd
    image: rhasspy/rhasspy-speakers-cli-hermes
    tty: true
  speech_to_text:
    command: --acoustic-model /profiles/de/acoustic_model --dictionary /profiles/de/dictionary.txt
      --language-model /profiles/de/language_model.txt --debug --host mosquitto --port
      1883 --site-id default --intent-graph /profiles/de/intent_graph.pickle.gz --base-dictionary
      /profiles/de/base_dictionary.txt --base-dictionary /profiles/de/custom_words.txt
      --dictionary-casing lower --g2p-model /profiles/de/g2p.fst --unknown-words /profiles/de/unknown_words.txt
      --base-language-model-fst /profiles/de/base_language_model.fst --base-language-model-weight
      0 --mixed-language-model-fst /profiles/de/mixed.fst --voice-skip-seconds 0 --voice-min-seconds
      1 --voice-speech-seconds 0.3 --voice-silence-seconds 1.5 --voice-before-seconds
      0.5 --voice-sensitivity 1
    depends_on:
    - mqtt
    image: rhasspy/rhasspy-asr-pocketsphinx-hermes
    tty: true
    volumes:
    - /profiles:/profiles
  text_to_speech:
    command: --tts-command 'espeak --stdout -v {lang} -v de+f4 -s 120 -g 1 -p 45'
      --voices-command 'espeak --voices | tail -n +2 | awk '"'"'{ print $2,$4 }'"'"''
      --language de --debug --host mosquitto --port 1883 --site-id default
    depends_on:
    - mqtt
    image: rhasspy/rhasspy-tts-cli-hermes
    tty: true
  wake:
    command: --keyword /profiles/de/raven/heytrixie --probability-threshold 0.58 --minimum-matches
      1 --average-templates --vad-sensitivity 1 --debug --host mosquitto --port 1883
      --site-id default
    depends_on:
    - mqtt
    image: rhasspy/rhasspy-wake-raven-hermes
    tty: true
    volumes:
    - /profiles:/profiles
version: '2'
